# Generated by Django 2.2.14 on 2020-09-23 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ranking',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Uganda', max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('streetaddress', models.CharField(max_length=255)),
                ('apartmentadress', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
