# Generated by Django 2.2.14 on 2020-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200923_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartmentadress',
        ),
        migrations.AddField(
            model_name='address',
            name='apartmentaddress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='streetaddress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
